GET http://localhost:7000/liveness
Accept: application/json

###

GET http://localhost:7000/v1/exchange/currencies
Accept: application/json

{}

### 

GET http://localhost:7000/v1/exchange/quotation?from=USD&to=BRL&val=5.0
Accept: application/json
